spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true  # query 가 정렬돼서 로그가 찍힘
    generate-ddl: true  # 자동으로 entity 에서 활용하는 테이블들을 생성하는 opt 이다. default 는 false 다.
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager   # jdbc: API 설정, mysql: 클라이언트 드라이버 설정, //localhost: url 주소
    username: root
    password: scarlett@1   # spring 에서 지정하는 initialization mode 동작한다는 의미
  sql:
    init:
      mode: always  # spring 에서 지정하는 initialization mode 동작한다는 의미. 즉, 스키마.sql 파일 또는 data.sql 파일을 로딩해서 해당 쿼리들을 실행 -> h2 DB 대신 mysql DB를 사용하게 되면서 필요하게 된 설정
